### ISSUE TITLE
Need to pass CFLAG -fPIC when building for QNX

### ISSUE THREAD

**Issue by asobhy-qnx** [ros2/poco_vendor#27]
Need to pass CFLAG -fPIC when building for QNX. this issue can be solved in two ways:

option 1:
replace:
https://github.com/ros2/poco_vendor/blob/3f23e18f8d71e979e03395d860bc3053d3162ae6/CMakeLists.txt#L25
with:
list(APPEND extra_cmake_args "-DCMAKE_C_FLAGS=${CMAKE_C_FLAGS} -Wno-shift-negative-value") 

option 2:
edit the CMakeLists.txt file and include this line before ExternalProject_Add()
  if(QNX)
    list(APPEND extra_cmake_args "-DCMAKE_C_FLAGS=${CMAKE_C_FLAGS} -fPIC")
  endif()

Please let me know which one you prefer so I can make a PR with, Thanks.

**Comment by asobhy-qnx** [comment]
@dirk-thomas

**Comment by clalancette** [comment]
@asobhy-qnx For what it is worth, this repository is no longer used as of Foxy.  So any solution here will just be for Dashing and Eloquent.

Regardless, if you still want to pursue this, I'd go for option 1.  That ensures that things work for any other C_FLAGS that the user might be specifying.  Are you willing to submit a PR to do that?

**Comment by asobhy-qnx** [comment]
ok great. Yes I will submit a PR. We're interested in Dashing as well.

**Comment by clalancette** [comment]
This was fixed by #28, so closing.
