### ISSUE TITLE
Github throttling download of poco archive?

### ISSUE THREAD

**Issue by sloretz** [ros2/poco_vendor#8]
I had some issues on mini2 yesterday where the download for https://github.com/pocoproject/poco/archive/poco-1.7.7-release.tar.gz was really really slow. It hit the 600s timeout repeatedly before giving up and failing. At the same time the download completed instantly from my computer, so I suspect this is another case of a build machine getting throttled for downloading something too much.

One option is to include the archive in this repo, however that is still downloading it from github. Another option is to set up a mirror and have this repo try to download from it if the github link fails.

Here's an example
http://ci.ros2.org/job/ci_osx/2596/consoleText

**Comment by sloretz** [comment]
Still an issue today
http://ci.ros2.org/job/ci_osx/2598/console

**Comment by sloretz** [comment]
On mini2 the download is slow using wget, curl, curl with a random user agent, and safari. An internet speed test on mini2 shows ~50Mb down. Transferring a 300MB file between my machine and mini2 took a couple seconds both directions. Seems like github throttling is most likely.

**Comment by dirk-thomas** [comment]
Since this works on newer builds on mini2 with normal speed again and there is nothing we can do about it (except setting up caching infrastructure) I would suggest to close this ticket.

**Comment by sloretz** [comment]
Sounds good to me.
